[workspace]
authors = ["Jeppe Klitgaard <hi@jeppe.science>"]
channels = ["conda-forge"]
name = "30760 Inverse Problems and Machine Learning in Earth and Space Physics"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
notebook = ">=7.5.3,<8"
netcdf4 = ">=1.7.4,<2"
cartopy = ">=0.25.0,<0.26"
matplotlib = ">=3.10.8,<4"
pandas = ">=3.0.0,<4"
cython = ">=3.2.4,<4"
h5py = ">=3.15.1,<4"
seaborn = ">=0.13.2,<0.14"
scikit-learn = ">=1.8.0,<2"
gstools = ">=1.7.0,<2"
astropy = ">=7.2.0,<8"
astroml = ">=1.0.2.post1,<2"
scikit-fmm = ">=2025.6.23,<2026"
hdf5storage = ">=0.1.19,<0.2"
bspline = ">=0.1.1,<0.2"
pytorch = ">=2.10.0,<3"
ipympl = ">=0.10.0,<0.11"
ffmpeg = ">=8.0.1,<9"
polars = ">=1.38.1,<2"
tqdm = ">=4.67.3,<5"
ipykernel = "<7"
numba = ">=0.64.0,<0.65"
ipython = ">=9.11.0,<10"

[pypi-dependencies]
chaosmagpy = ">=0.13.1, <0.14"
scikit-traveltime = ">=0.1.4, <0.2"
